### ISSUE TITLE
High CPU/IO usage

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/smash#136] opened 2021-01-04 11:26 UTC
After a half a day, is this correct behaviour?

![obrazek](https://user-images.githubusercontent.com/58650764/103530401-a58d8980-4e87-11eb-9f93-3f42230d74c8.png)

(ssd) 
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          66.72    0.17    9.76    0.24    0.00   23.12
```

If so, isnt planned some rate-limit? 

![obrazek](https://user-images.githubusercontent.com/58650764/103530493-d4a3fb00-4e87-11eb-9a49-b9afc7329128.png)

**Comment by ksaric** [comment] 2021-01-04 14:17
@cardanians Please provide the version you are using. I presumed we are talking about the latest `master`.

The screenshot provides the logs which show that it must have been running more than a day since we see the retry spanning more than 10 days and the retry count being > 20.
The actual fetch mechanism is rate limited since it has exponential backoff and it also works in a separate thread. All the requests are in a queue and are executed from that single thread.

Now, it could be that the node is running along with SMASH and that it is syncing AND retrying at the same time and it could be that the CPU usage is peaking, but it should not be the case that it is behaving like this all the time.

If you want to see what SMASH is using without the actual syncing with the blockchain and fetching, you can use `run-app` to see the usage (you don't need the node running).
Then you can turn on just the node to see how much that is consuming.
And in the end, run both and see the results when syncing and when synced.

I will close this issue, for now, if you do find something more tangible to reproduce, please provide more information and I will try to reproduce it.

Thanks.

**Closed by ksaric** 2021-01-04 14:17 UTC
